#!/usr/bin/env bash

sleep 1

setxkbmap -layout us,ru,ua
setxkbmap -option grp:alt_shift_toggle

sleep 1 && firejail --noroot --apparmor --seccomp --name=clipit /usr/bin/clipit &

sleep 1 && aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log &

# sleep ss -lpntu